# Theme configuration
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
title: Mammoth Investing Support
description: Support documentation and FAQs for Mammoth Investing users.
baseurl: "" # Leave empty for user sites (username.github.io), or set to "/repo-name" for project sites
url: "https://mammothinvesting.github.io" # Replace with your GitHub Pages URL
